package:
  name: aocutils
  version: "0.3.0"

source:
  git_rev: 0.3.0
  git_url: https://github.com/floatingpointstack/aoc-utils.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pythonocc-core

test:
  imports:
    - aocutils

about:
  home: https://github.com/floatingpointstack/aoc-utils
  license: GPL